import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const poet = ({ data }) => {
    console.log(data)
    return (
        <>
            <Head>
                <title>Poet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>poet</h1>

            </main>
        </>
    );
};


export const getStaticProps = async (context) => {

    const response = await fetch(`https://api.ganjoor.net/api/ganjoor/poet?url=/${context.params.fullUrl}`)
    const data = await response.json()
    return {
        props: { data }
    }

}

export const getStaticPaths = async () => {

    const response = await fetch(`https://api.ganjoor.net/api/ganjoor/centuries`)
    const data = await response.json()
    const poets = data.map(p => p.poets)
    const paths = poets.map(fullUrl => (
        { params: { poet: `${fullUrl.fullUrl.split("/")[1]}` },  }
    ))
    console.log(paths)
    return {
        paths,
        fallback: false
    }
}



export default poet;

