import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const poets = ({ data }) => {
  console.log(data)

  return (
    <>
      <Head>
        <title>Poets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>poets</h1>

        {

          data.map(item => {
            return (
              item.poets.map(p => {
                return (
                  <div key={p.id}>
                    <Link href={`${p.fullUrl}`}
                    >
                      <div >
                        <img className='' src={`https://api.ganjoor.net${p.imageUrl}`} alt={p.name} />
                      </div>
                        <h6>{p.nickname}</h6>
                    </Link>
                  </div>
                );
              })
            )
          })
        }
      </main>
    </>
  );
};



export const getStaticProps = async () => {

  const response = await fetch('https://api.ganjoor.net/api/ganjoor/centuries')
  const data = await response.json()
  return {
    props: { data }
  }

}



export default poets;